language: node_js
node_js: 
  - "10"
deploy:
  provider: source
  skip-cleanup: true
  github-token: $REPO_TOKEN
  keep-history: true
  on:
    branch: master
branches:
  only:
  - source
cache:
  apt: true
  yarn: true
  directories:
  - node_modules
addons:
  ssh_known_hosts: 47.52.172.108
before_install:
- openssl aes-256-cbc -K $encrypted_73581c3740bd_key -iv $encrypted_73581c3740bd_iv
  -in id_rsa_deploy.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git config  user.name "zhangrb"
- git config  user.email "mrzhangrb@outlook.com"
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
install:
- yarn
script:
- hexo clean
- hexo generate
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://$REPO_TOKEN@github.com/Mrzrb/zhangrbblogrelease.git
  master
- ssh root@47.52.172.108 "/usr/share/nginx/html/zhangrb.com.blog/deploy.sh"
